# Generated by Django 5.0.4 on 2024-05-16 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_initial"),
        ("my_house", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_recurring", models.BooleanField(default=False)),
                ("period", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Перечень платежей",
                "verbose_name_plural": "Перечень платежей",
            },
        ),
        migrations.AlterField(
            model_name="debt",
            name="payment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="my_house.payment"
            ),
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "verbose_name": "Принятие платежей",
                "verbose_name_plural": "Принятие платежей",
            },
        ),
        migrations.RemoveField(
            model_name="payment",
            name="is_recurring",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="name",
        ),
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="flat",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="home.flat"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидание"),
                    ("approved", "Оплачено"),
                    ("rejected", "Отклонено"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_house.paymenttype",
            ),
        ),
        migrations.DeleteModel(
            name="UserPayment",
        ),
    ]
