# Generated by Django 5.0.6 on 2024-06-01 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_house', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
