# Generated by Django 5.0.6 on 2024-06-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_house', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domkom',
            options={'verbose_name': 'Домком', 'verbose_name_plural': 'Домком'},
        ),
    ]
