version: '3'

services:
  api:
    build: .
    command: >
      sh -c "daphne -b 0.0.0.0 -p 8000 core.asgi:application"
    container_name: beka
    ports:
      - '8001:8000'
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - migration
    volumes:
      - static_volume:/usr/src/app/back_static
      - media_volume:/usr/src/app/back_media

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: '${DATABASE_NAME}'
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      TZ: Asia/Bishkek
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  migration:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate"
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "81:81"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/back_static
      - media_volume:/usr/src/app/back_media
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume:
  media_volume:
