# Generated by Django 5.0.6 on 2024-06-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_status',
            field=models.CharField(choices=[('APPROVED', 'Одобрен'), ('NOT_APPROVED', 'Не одобрен'), ('PENDING', 'В ожидании'), ('ARCHIVED', 'Архивирован')], default='PENDING', max_length=12, null=True, verbose_name='Одобрение'),
        ),
    ]
