# Generated by Django 5.0.6 on 2024-06-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='is_verif',
            field=models.BooleanField(default=False),
        ),
    ]
