# Generated by Django 5.0.6 on 2024-06-06 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_initial'),
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flatowner',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'OWNER'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='apartmenthistory',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='home.flatowner', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='flattenant',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.flat', verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='flattenant',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.flatowner', verbose_name='Владелец квартиры'),
        ),
        migrations.AddField(
            model_name='flattenant',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'TENANT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Арендатор'),
        ),
        migrations.AddField(
            model_name='apartmenthistory',
            name='tenant',
            field=models.ManyToManyField(blank=True, related_name='resident_history', to='home.flattenant', verbose_name='Арендатор'),
        ),
        migrations.AddField(
            model_name='flat',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.house', verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='request_vote_news',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='От пользователя'),
        ),
        migrations.AddField(
            model_name='tsj',
            name='house',
            field=models.ManyToManyField(to='home.house', verbose_name='Дома для ТСЖ'),
        ),
        migrations.AddField(
            model_name='request_vote_news',
            name='tsj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tsj', verbose_name='ТСЖ'),
        ),
        migrations.AddField(
            model_name='flattenant',
            name='tsj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tsj', verbose_name='ТСЖ'),
        ),
        migrations.AddField(
            model_name='flatowner',
            name='tsj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tsj', verbose_name='ТСЖ'),
        ),
        migrations.AddField(
            model_name='vote',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.room', verbose_name='Канал обсуждения'),
        ),
        migrations.AddField(
            model_name='vote',
            name='tjs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tsj', verbose_name='Выберите ТСЖ'),
        ),
        migrations.AddField(
            model_name='voteresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='voteresult',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='home.vote', verbose_name='Голосование'),
        ),
        migrations.AddField(
            model_name='voteview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='voteview',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='home.vote', verbose_name='Голосование'),
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('house', 'number')},
        ),
    ]
