# Generated by Django 5.0.6 on 2024-06-10 03:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request_Vote_News',
            new_name='RequestVoteNews',
        ),
    ]
