# Generated by Django 5.0.6 on 2024-05-31 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsview',
            name='news',
        ),
        migrations.RemoveField(
            model_name='newsview',
            name='user',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsView',
        ),
    ]
