# Generated by Django 5.0.6 on 2024-06-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_request_vote_news_requestvotenews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestvotenews',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='requestvotenews',
            name='link',
        ),
    ]
