# Generated by Django 5.0.6 on 2024-05-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_vote_created_date_alter_voteresult_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voteresult',
            options={'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.AlterModelOptions(
            name='voteview',
            options={'verbose_name': 'Просмотр', 'verbose_name_plural': 'Просмотры'},
        ),
    ]
