# Generated by Django 5.0.6 on 2024-06-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_domkomrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('web_site', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.housedeveloper'),
        ),
    ]
