# Generated by Django 5.0.6 on 2024-06-10 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_housephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housephoto',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='home.house'),
        ),
    ]
