# Generated by Django 5.0.6 on 2024-06-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_housephoto_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='flattenant',
            name='access_to_chats',
            field=models.BooleanField(default=False),
        ),
    ]
