# Generated by Django 5.0.6 on 2024-06-21 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_requestvotenews_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='domkomrole',
            name='tsj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tsj'),
        ),
    ]
