# Generated by Django 5.0.6 on 2024-06-21 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_domkomrole_tsj'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together=set(),
        ),
    ]
