# Generated by Django 5.0.6 on 2024-06-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_flat_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='date_finish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
