# Generated by Django 5.0.6 on 2024-06-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_vote_date_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsj',
            name='house',
            field=models.ManyToManyField(related_name='house_tsj', to='home.house', verbose_name='Дома для ТСЖ'),
        ),
    ]
