# Generated by Django 5.0.6 on 2024-05-31 10:36

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_remove_newsview_news_remove_newsview_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Новости', 'Новости'), ('Объявления', 'Объявления')], max_length=100, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание')),
                ('link', models.URLField(verbose_name='Ссылка на источник')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('tsj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tsj', verbose_name='ТСЖ')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Добавить новость',
            },
        ),
        migrations.CreateModel(
            name='NewsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blogs.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Просмотр новости',
                'verbose_name_plural': 'Просмотры новостей',
            },
        ),
    ]
