# Generated by Django 5.0.6 on 2024-06-04 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tsj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tsj', verbose_name='ТСЖ'),
        ),
        migrations.AddField(
            model_name='newsview',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blogs.news'),
        ),
    ]
