# Generated by Django 5.0.6 on 2024-06-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_approve',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
