from django.urls import path
from .views import (
    TSJListView, HouseListView, FlatOwnerListView, FlatTenantListView, FlatListView,
    NewsListView, RequestListView, HelpInfoListView, VoteListView,
    TSJCreateView, HouseCreateView, FlatOwnerCreateView, FlatTenantCreateView,
    FlatCreateView, NewsCreateView, RequestCreateView, HelpInfoCreateView, VoteCreateView,
    TSJUpdateView, HouseUpdateView, FlatOwnerUpdateView, FlatTenantUpdateView,
    FlatUpdateView, NewsUpdateView, RequestUpdateView, HelpInfoUpdateView, VoteUpdateView,
    TSJDestroyView, HouseDestroyView, FlatOwnerDestroyView, FlatTenantDestroyView,
    FlatDestroyView, NewsDestroyView, RequestDestroyView, HelpInfoDestroyView, VoteDestroyView
)


urlpatterns = [
    path('tsj/list', TSJListView.as_view(), name='tsj-list'),
    path('tsj/create/', TSJCreateView.as_view(), name='create-tsj'),
    path('tsj/<int:pk>/update/', TSJUpdateView.as_view(), name='update-tsj'),
    path('tsj/<int:pk>/delete/', TSJDestroyView.as_view(), name='delete-tsj'),
    path('houses/list', HouseListView.as_view(), name='house-list'),
    path('house/create/', HouseCreateView.as_view(), name='create-house'),
    path('houses/<int:pk>/update/', HouseUpdateView.as_view(), name='update-house'),
    path('houses/<int:pk>/delete/', HouseDestroyView.as_view(), name='delete-house'),
    path('flat-owners/list', FlatOwnerListView.as_view(), name='flat-owner-list'),
    path('flat-owner/create/', FlatOwnerCreateView.as_view(), name='create-flat-owner'),
    path('flat-owners/<int:pk>/update/', FlatOwnerUpdateView.as_view(), name='update-flat-owner'),
    path('flat-owners/<int:pk>/delete/', FlatOwnerDestroyView.as_view(), name='delete-flat-owner'),
    path('flat-tenants/list', FlatTenantListView.as_view(), name='flat-tenant-list'),
    path('flat-tenant/create/', FlatTenantCreateView.as_view(), name='create-flat-tenant'),
    path('flat-tenants/<int:pk>/update/', FlatTenantUpdateView.as_view(), name='update-flat-tenant'),
    path('flat-tenants/<int:pk>/delete/', FlatTenantDestroyView.as_view(), name='delete-flat-tenant'),
    path('flats/list', FlatListView.as_view(), name='flat-list'),
    path('flat/create/', FlatCreateView.as_view(), name='create-flat'),
    path('flats/<int:pk>/update/', FlatUpdateView.as_view(), name='update-flat'),
    path('flats/<int:pk>/delete/', FlatDestroyView.as_view(), name='delete-flat'),
    path('news/list', NewsListView.as_view(), name='news-list'),
    path('news/create/', NewsCreateView.as_view(), name='create-news'),
    path('news/<int:pk>/update/', NewsUpdateView.as_view(), name='update-news'),
    path('news/<int:pk>/delete/', NewsDestroyView.as_view(), name='delete-news'),
    path('requests/list', RequestListView.as_view(), name='request-list'),
    path('request/create/', RequestCreateView.as_view(), name='create-request'),
    path('requests/<int:pk>/update/', RequestUpdateView.as_view(), name='update-request'),
    path('requests/<int:pk>/delete/', RequestDestroyView.as_view(), name='delete-request'),
    path('help-info/list', HelpInfoListView.as_view(), name='help-info-list'),
    path('help-info/create/', HelpInfoCreateView.as_view(), name='create-help-info'),
    path('help-info/<int:pk>/update/', HelpInfoUpdateView.as_view(), name='update-help-info'),
    path('help-info/<int:pk>/delete/', HelpInfoDestroyView.as_view(), name='delete-help-info'),
    path('votes/list', VoteListView.as_view(), name='vote-list'),
    path('vote/create/', VoteCreateView.as_view(), name='create-vote'),
    path('votes/<int:pk>/update/', VoteUpdateView.as_view(), name='update-vote'),
    path('votes/<int:pk>/delete/', VoteDestroyView.as_view(), name='delete-vote'),
]
