# Generated by Django 5.0.6 on 2024-06-01 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_remove_newsview_news_remove_newsview_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_recurring', models.BooleanField(default=False)),
                ('period', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Перечень платежей',
                'verbose_name_plural': 'Перечень платежей',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Оплачено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('flat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.flat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.paymenttype')),
            ],
            options={
                'verbose_name': 'Принятие платежей',
                'verbose_name_plural': 'Принятие платежей',
            },
        ),
    ]
