# Generated by Django 5.0.6 on 2024-06-04 17:47

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, default='avatars/default_avatar', null=True, upload_to='avatars/', verbose_name='Фото')),
                ('user', models.OneToOneField(help_text='Чей профиль', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Пример: +996700777777', max_length=128, null=True, region=None, verbose_name='Номер телефона')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=50, null=True, verbose_name='Статус')),
                ('name_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.flatowner', verbose_name='Владелец')),
                ('number_flat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.flat', verbose_name='Номер квартиры')),
                ('tsj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tsj', verbose_name='ТСЖ')),
            ],
            options={
                'verbose_name': 'Запросы',
                'verbose_name_plural': 'Запросы',
            },
        ),
        migrations.CreateModel(
            name='ResidenceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100, null=True, verbose_name='Фамилия владельца')),
                ('tenant_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия жителя')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Точный адрес')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата выдачи')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Выдано')),
            ],
            options={
                'verbose_name': 'Справка о местожительстве',
                'verbose_name_plural': 'Справки о местожительстве',
            },
        ),
    ]
