# Generated by Django 5.0.6 on 2024-06-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_discussion',
            field=models.BooleanField(default=False),
        ),
    ]
