# Generated by Django 5.0.6 on 2024-05-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_remove_room_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_voting',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
